# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema.cake_web]
file = "../cake-web-user/src/schema.rs"
with_docs = true
custom_type_derives = ["diesel::query_builder::QueryId"]
schema="cake_web"

[migrations_directory]
dir = "migrations"
