[package]
name = "loom_exex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
loom-broadcast-accounts.workspace = true
loom-broadcast-broadcaster.workspace = true
loom-core-actors.workspace = true
loom-core-block-history.workspace = true
loom-core-blockchain.workspace = true
loom-core-blockchain-actors.workspace = true
loom-core-router.workspace = true
loom-core-topology.workspace = true
loom-defi-entities.workspace = true
loom-defi-events.workspace = true
loom-defi-market.workspace = true
loom-defi-preloader.workspace = true
loom-defi-price.workspace = true
loom-defi-types.workspace = true
loom-evm-db.workspace = true
loom-evm-utils.workspace = true
loom-executor-estimator.workspace = true
loom-node-actor-config.workspace = true
loom-node-debug-provider.workspace = true
loom-node-exex.workspace = true
loom-node-json-rpc.workspace = true
loom-protocol-pools.workspace = true
loom-rpc-handler.workspace = true
loom-rpc-state.workspace = true
loom-storage-db.workspace = true
loom-strategy-backrun.workspace = true
loom-strategy-merger.workspace = true


axum.workspace = true
clap.workspace = true
eyre.workspace = true
futures-util.workspace = true
hex.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

alloy.workspace = true

# reth
reth.workspace = true
reth-chainspec.workspace = true
reth-db.workspace = true
reth-execution-types.workspace = true
reth-exex.workspace = true
reth-node-api.workspace = true
reth-node-core.workspace = true
reth-node-ethereum.workspace = true
reth-primitives.workspace = true
reth-provider.workspace = true
reth-rpc-types-compat.workspace = true


[dev-dependencies]
reth-exex-test-utils.workspace = true
reth-testing-utils.workspace = true
