[package]
name = "loom_exex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
loom = { workspace = true, features = ["full", "strategy-full"] }

axum.workspace = true
clap.workspace = true
eyre.workspace = true
futures-util.workspace = true
hex.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

alloy.workspace = true

# reth
reth.workspace = true
reth-chainspec.workspace = true
reth-db.workspace = true
reth-execution-types.workspace = true
reth-exex.workspace = true
reth-node-api.workspace = true
reth-node-core.workspace = true
reth-node-ethereum.workspace = true
reth-primitives.workspace = true
reth-provider.workspace = true
reth-rpc-types-compat.workspace = true


[dev-dependencies]
reth-exex-test-utils.workspace = true
reth-testing-utils.workspace = true
