[package]
name = "loom_exex"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[dependencies]
tokio.workspace = true
eyre.workspace = true
futures-util.workspace = true
hex.workspace = true
clap.workspace = true

alloy.workspace = true

reth.workspace = true
reth-db.workspace = true
reth-chainspec.workspace = true
reth-provider.workspace = true
reth-exex.workspace = true
reth-node-api.workspace = true
reth-node-ethereum.workspace = true
reth-rpc-types.workspace = true
reth-rpc-types-compat.workspace = true
reth-primitives.workspace = true
reth-tracing.workspace = true
reth-execution-types.workspace = true

loom-actors.workspace = true
loom-utils.workspace = true
defi-actors.workspace = true
defi-blockchain.workspace = true
defi-events.workspace = true
defi-types.workspace = true
debug-provider.workspace = true
loom-topology.workspace = true



[dev-dependencies]
reth-exex-test-utils.workspace = true
reth-testing-utils.workspace = true

