[package]
name = "loom-core-blockchain-actors"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
loom-broadcast-accounts.workspace = true
loom-broadcast-broadcaster.workspace = true
loom-broadcast-flashbots.workspace = true
loom-core-actors.workspace = true
loom-core-block-history.workspace = true
loom-core-blockchain.workspace = true
loom-core-mempool.workspace = true
loom-core-router.workspace = true
loom-defi-address-book.workspace = true
loom-defi-health-monitor.workspace = true
loom-defi-market.workspace = true
loom-defi-pools.workspace = true
loom-defi-preloader.workspace = true
loom-defi-price.workspace = true
loom-evm-db.workspace = true
loom-evm-utils.workspace = true
loom-execution-estimator.workspace = true
loom-execution-multicaller.workspace = true
loom-metrics.workspace = true
loom-node-actor-config.workspace = true
loom-node-db-access = { workspace = true, optional = true }
loom-node-debug-provider.workspace = true
loom-node-grpc.workspace = true
loom-node-json-rpc.workspace = true
loom-rpc-handler.workspace = true
loom-rpc-state.workspace = true
loom-storage-db.workspace = true
loom-strategy-backrun.workspace = true
loom-strategy-merger.workspace = true
loom-types-entities.workspace = true

axum.workspace = true
eyre.workspace = true
tokio-util.workspace = true

# alloy
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-transport.workspace = true

#revm
revm.workspace = true

[features]
db-access = ["dep:loom-node-db-access"]
