[package]
name = "loom-node-json-rpc"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
loom-core-actors.workspace = true
loom-core-actors-macros.workspace = true
loom-core-blockchain.workspace = true
loom-defi-events.workspace = true
loom-defi-types.workspace = true
loom-node-actor-config.workspace = true
loom-node-db-access.workspace = true
loom-node-debug-provider.workspace = true

chrono.workspace = true
eyre.workspace = true
futures.workspace = true
tokio.workspace = true
tracing.workspace = true

# alloy
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-pubsub.workspace = true
alloy-rpc-types.workspace = true
alloy-transport.workspace = true


[dev-dependencies]
alloy-rpc-client.workspace = true
env_logger.workspace = true
