[package]
name = "loom"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
debug-provider.workspace = true
defi-abi.workspace = true
defi-actors.workspace = true
defi-address-book.workspace = true
defi-blockchain.workspace = true
defi-entities.workspace = true
defi-events.workspace = true
defi-pools.workspace = true
defi-types.workspace = true
flashbots.workspace = true
loom-actors.workspace = true
loom-actors-macros.workspace = true
loom-multicaller.workspace = true
loom-revm-db.workspace = true
loom-topology.workspace = true
loom-utils.workspace = true
