[package]
name = "loom"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
loom-broadcast-flashbots.workspace = true
loom-core-actors.workspace = true
loom-core-actors-macros.workspace = true
loom-core-blockchain.workspace = true
loom-core-topology.workspace = true
loom-defi-entities.workspace = true
loom-defi-events.workspace = true
loom-defi-types.workspace = true
loom-evm-db.workspace = true
loom-evm-utils.workspace = true
loom-executor-multicaller.workspace = true
loom-node-debug-provider.workspace = true
loom-protocol-abi.workspace = true
loom-protocol-address-book.workspace = true
loom-protocol-pools.workspace = true
