[package]
name = "loom-strategy-backrun"
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
loom-core-actors.workspace = true
loom-core-actors-macros.workspace = true
loom-core-blockchain.workspace = true
loom-defi-pools.workspace = true
loom-evm-db.workspace = true
loom-node-debug-provider.workspace = true
loom-types-blockchain.workspace = true
loom-types-entities.workspace = true
loom-types-events.workspace = true

chrono.workspace = true
eyre.workspace = true
lazy_static.workspace = true
num_cpus.workspace = true
rayon.workspace = true
revm.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true

# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-provider.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-types-trace.workspace = true
alloy-transport.workspace = true

[[bench]]
harness = false
name = "swap_calculation_bench"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["async_tokio"] }
