name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    if: github.repository == 'dexloom/loom'
    name: make fmt-check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable

      - run: 'echo "pub const KEY_ENCRYPTION_PWD: [u8; 16] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];" > crates/defi-entities/src/private.rs'
      - run: make fmt-check

  taplo:
    if: github.repository == 'dexloom/loom'
    name: make taplo-check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@clippy
      - run: cargo install taplo-cli --version ^0.9 --locked
      - run: make taplo-check

  clippy:
    if: github.repository == 'dexloom/loom'
    name: make clippy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@clippy
        with:
          toolchain: "1.82"
      - uses: Swatinem/rust-cache@v2
      - uses: arduino/setup-protoc@v3

      - run: 'echo "pub const KEY_ENCRYPTION_PWD: [u8; 16] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];" > crates/defi-entities/src/private.rs'
      # workaround for latest stable rust
      - run: cargo +1.82 clippy --all-targets --all-features -- -D warnings