name: Test

on:
  push:
    branches: [main]
  workflow_run:
    workflows: [Lint]
    types: [completed]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    if: github.repository == 'dexloom/loom'
    name: make test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      MAINNET_HTTP: ${{ secrets.MAINNET_HTTP }}
      MAINNET_WS: ${{ secrets.MAINNET_WS }}
      RUST_LOG: info
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_branch }}
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: arduino/setup-protoc@v3
      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: 'echo "pub const KEY_ENCRYPTION_PWD: [u8; 16] = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];" > crates/defi-entities/src/private.rs'
      - run: make test
      - run: make swap-test-all